name: EveryWorldSpawn
main: ru.lmrbooml.EveryWorldSpawn.Ewspawn
version: 1.0.1
author: l_MrBoom_l
description: "Добавляет команды /setspawn и /spawn, а также даёт возможность установить отдельные точки спавна для каждого мира."

commands:
  setspawn:
    usage: "§cИспользование: /setspawn [ < [мир] <x> <y> <z> > [<yaw> <pitch>] ]"
    permission: ewspawn.setspawn
    description: "Устанавливает точку спавна."
  spawn:
    usage: "§cИспользование: /spawn [игрок]"
    permission: ewspawn.spawn
    description: "Телепортирует вас или указанного игрока на спавн."
  ewspawn:
    usage: "§cИспользование: /ewspawn"
    permission: ewspawn.help
    description: "Отображает список команд плагина EveryWorldSpawn."

permissions:
  ewspawn.*:
    description: "Даёт доступ ко всем командам плагина EveryWorldSpawn."
    default: op
    children:
      ewspawn.setspawn: true
      ewspawn.spawn: true
      ewspawn.help: true
      ewspawn.reload: true
      ewspawn.info: true
  ewspawn.help:
    description: "Даёт доступ к списку команд EveryWorldSpawn."
    default: true
  ewspawn.reload:
    description: "Даёт доступ к команде перезагрузки плагина."
    default: false
  ewspawn.info:
    description: "Даёт доступ к информации о плагине."
    default: true
  ewspawn.setspawn:
    description: "Даёт доступ к команде установки точки спавна."
    default: false
  ewspawn.spawn:
    description: "Даёт возможность телепортироваться на спавн."
    default: true
    children:
      ewspawn.spawn.others: false
  ewspawn.spawn.others:
    description: "Даёт возможность телепортировать других игроков на спавн."
    default: false
    children:
      ewspawn.spawn.others.silent: false
  ewspawn.spawn.others.silent:
    description: "Даёт возможность телепортировать других игроков на спавн анонимно."
    default: false